---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: tribalscaledocker/node
    tag: '8-alpine-aws'

inputs:
  - name: server-resource
outputs:
  - name: output-resource
caches:
  - path: output-resource/node_modules

run:
  path: sh
  args:
  - -exc
  - |
    cd server-resource
    npm install --no-progress
    npm install --no-progress --dev-only
    npm run build
    cp -r . ../output-resource